<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "functestexmpl"
 *
 * Auto generated by Extension Builder 2016-12-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Functional Test Example',
	'description' => 'Functional Test Example Extension',
	'category' => 'example',
	'author' => 'Philipp Bauer',
	'author_email' => 'hello@philippbauer.org',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);